# ===============================
# CONFIGURAÇÕES DO SERVIDOR WEB
# ===============================
server.port=8081
spring.application.name=order-delivery-service

# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS 
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURAÇÕES DO RABBITMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.listener.simple.default-requeue-rejected=false